version: '3.8'

volumes:
  data:

services:
  veritis-mssql:
    container_name: sql-server
    build: .
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password
      - MSSQL_PID=Developer
      - TZ=UTC
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/share
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'password' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s